version: '3'
services:
  web:
    build: .
    container_name: web-app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run

  db:
    image: busybox
    container_name: flask-db
    